[tool.poetry]
name = "astrobro"
version = "0.1.0"
description = ""
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
package-mode = false
repository = "https://github.com/hoishing/astrobro"
homepage = "https://astrobro.streamlit.app"

[tool.poetry.dependencies]
python = "^3.12"
natal = { path = "../natal", develop = true }
streamlit = "*"
watchdog = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
