[tool.poetry]
name = "astrobro"
version = "0.3.0"
description = ""
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
package-mode = false
repository = "https://github.com/hoishing/astrobro"
homepage = "https://astrobro.streamlit.app"

[tool.poetry.dependencies]
python = "^3.12"
# natal = "0.3.8"
streamlit = "*"
streamlit-shortcuts = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
natal = { path = "../natal", develop = true }
pytest = "*"
libsass = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
