[tool.poetry]
name = "astrobro"
version = "0.5.3"
description = ""
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
package-mode = false
repository = "https://github.com/hoishing/astrobro"
homepage = "https://astrobro.streamlit.app"

[tool.poetry.dependencies]
python = "^3.12"
natal = "^0.5.3"
streamlit = "^1.39.0"
streamlit-shortcuts = "^0.1.9"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
libsass = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
